### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by eventualbuddha**
All pretty minor. Each commit fixes one thing.

### CODE REVIEW

**Review by trentmwillis — APPROVED** [review]
Thanks, looks good to me. Restarting CI to see if it passes. I think a test is flaky.

**Comment by trentmwillis** [comment]
Still failing. After looking a bit closer, I think this may be due to dependency drift and us still testing against Phantom 1.x which I don't think we need to continue to do. We can likely drop this line: https://github.com/ember-engines/ember-asset-loader/blob/f8f1a448456697dbf128da27a15ca034d848763a/.travis.yml#L18

**Comment by eventualbuddha** [comment]
No big deal, these were just things I noticed when browsing the project.

*(Incidentally, spurious failures like this is why I disagree with the approach of not locking down dependencies in CI.)*

**Comment by rwjblue** [comment]
> (Incidentally, spurious failures like this is why I disagree with the approach of not locking down dependencies in CI.)

Noted (again)

**Comment by rwjblue** [comment]
CI was fixed (thanks @lennyburdette!) in https://github.com/ember-engines/ember-asset-loader/pull/66, this should pass with a rebase...

**Comment by eventualbuddha** [comment]
Okay, rebased.

**Review by rwjblue — APPROVED** [review]

**Comment by rwjblue** [comment]
Thank you @eventualbuddha!

**Pull request merged**
