### PR TITLE
Properly extend from Error base class

### PR DESCRIPTION
**Pull request by xg-wang**
Also add test to ensure `instanceof` and `stack`.

The `instanceof` test passed without the PR, but `stack` is missing on current HEAD.

### CODE REVIEW

**Comment by xg-wang** [comment]
Seems travis is broken
```
/home/travis/.yarn/lib/cli.js:45726
  let {
```

**Comment by xg-wang** [comment]
Seems saucelab's IE 10 `new Error().stack` doesn't exists although all online references say IE 10 has the `stack`...

**Comment by stefanpenner** [comment]
@xg-wang I suspect they only have stack after being thrown. (this at-least was common for old JS vm's)

**Comment by xg-wang** [comment]
@stefanpenner I think it's fine to have no stack on IE10, by doing a check in tests whether `new Error.stack` exists. What do you think?

**Comment by stefanpenner** [comment]
@xg-wang unfortunately then for browsers who require a throw, no stack will be provided. Hindering debugging.

example of how to implement with backward compat: https://github.com/emberjs/ember.js/blob/c7bbe293c66c3776e1c3851356d1e78e4b8c8ca5/packages/ember-debug/lib/deprecate.js#L82-L88

**Comment by xg-wang** [comment]
Drop IE9 support since it doesn't have `Error.prototype.stack`
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Stack#Browser_compatibility

**Comment by xg-wang** [comment]
@stefanpenner sauce is happy

**Comment by stefanpenner** [comment]
thanks, released as v0.5.1 🎉

**Pull request merged**
