### PR TITLE
Removes needless Warning on resetLoadedAssetState  

### PR DESCRIPTION
**Pull request by villander**
It's solves the issue #74 

@rwjblue @dgeb

### CODE REVIEW

**Comment by rwjblue** [comment]
Looks like CI is installing yarn 1.13, but that version apparently _requires_ Node 6 (its using destructuring).

We should pin to a prior version in `.travis.yml` until we do a major bump dropping Node 4.

**Comment by rwjblue** [comment]
https://github.com/ember-engines/ember-asset-loader/pull/76 is attempting to fix that...

**Comment by villander** [comment]
thank you @rwjblue 🙏

**Comment by stefanpenner** [comment]
https://github.com/ember-engines/ember-asset-loader/pull/76 landed, can you rebase?

**Comment by stefanpenner** [comment]
I'm going to try and get the rest of the tests green tonight as well.

**Comment by stefanpenner** [comment]
rebased

**Comment by stefanpenner** [comment]
Speaking with @rwjblue this changes seems strange. We are wondering if we should simply drop the log entirely.

**Comment by rwjblue** [comment]
I'm not sure this is the direction we want to go here...

The log message here was _intended_ to be done each time you reset state. Making it a one time thing breaks the intent here.

IMHO, if we want to avoid log spew here and we don't find this particular warning useful / nice we should just remove it...

**Comment by villander** [comment]
Can I remove it then?

cc: @rwjblue

**Comment by stefanpenner** [comment]
Yup I think we should kill it.

**Comment by villander** [comment]
Done!

cc: @stefanpenner @rwjblue

**Review by rwjblue — APPROVED** [review]

**Comment by rwjblue** [comment]
Good to land, will try to merge and release in the AM...

**Comment by villander** [comment]
@rwjblue can we merge this ?

**Comment by villander** [comment]
@rwjblue @stefanpenner @dgeb we need merge this, please

**Pull request merged**
