### PR TITLE
add .git to npmignore

### PR DESCRIPTION
**Pull request by ghost**
This could resolve the issue about the error EISGIT when performing npm-install.

### CODE REVIEW

**Review by rwjblue — APPROVED** [review]

**Comment by rwjblue** [comment]
Thanks!

**Comment by ghost** [comment]
@rwjblue No problem! I got this error with the update of ember-engines to version 0.8.0. If someone do a release of this package with the change, I could do a PR on ember-engines to use the fixed version of this package to avoid the error with git.

**Comment by rwjblue** [comment]
Published 0.6.1

**Comment by ghost** [comment]
Thanks à lot! I just did the PR on ember-engines as mentioned above.

**Pull request merged**
