### PR TITLE
Refactor tests to use broccoli-test-helper API.

### PR DESCRIPTION
**Pull request by rwjblue**

### CODE REVIEW

**Comment by rwjblue** [comment]
CI failed in Sauce Labs testing, seems completely unrelated to the changes in this PR.

```
not ok 191 Edge 14.14393 - Acceptance | asset-load: visiting a route which loads a bundle
    ---
        actual: >
            transparent
        expected: >
            transparent
        stack: >
               at Anonymous function (http://localhost:7000/assets/tests.js:34:7)
               at andThen (http://localhost:7000/assets/vendor.js:54320:5)
               at Anonymous function (http://localhost:7000/assets/vendor.js:54267:9)
               at isolate (http://localhost:7000/assets/vendor.js:55385:5)
               at Anonymous function (http://localhost:7000/assets/vendor.js:55328:9)
               at tryCatch (http://localhost:7000/assets/vendor.js:63472:7)
        message: >
            background color is different after css load
        Log: |
    ...
```

**Comment by rwjblue** [comment]
The same failure is affecting master builds: https://travis-ci.org/ember-engines/ember-asset-loader/jobs/262718572.

**Comment by trentmwillis** [comment]
Those tests are unfortunately a bit racy (tries to validate changes to the DOM before/after the CSS asset loads, which is an imperfect science for some browsers). Going to try restarting them...

**Comment by rwjblue** [comment]
Ahh, that makes sense.  Do you think we might be able to do a bit of polling to at least absorb some of the raciness?

**Review by trentmwillis — APPROVED** [review]
Changes seem good, :+1: on adding `co`.

**Comment by trentmwillis** [comment]
> Do you think we might be able to do a bit of polling to at least absorb some of the raciness?

Seems like a good idea to me.

**Comment by trentmwillis** [comment]
Tests are green now. Going to merge and we can try to improve those other tests in another PR.

**Pull request merged**
